### PR TITLE
Fix showing duplicate result of dhos on the explore page

### PR DESCRIPTION
**Pull request by arsenijesavic**

### CODE REVIEW

**Review by pugakn — CHANGES_REQUESTED** [review]
These changes are causing a bug on the DAO sidebar were all dao logos looks like the same
image


Should look like this:
image

@arsenijesavic

**Comment by arsenijesavic** [comment]
@pugakn I'm not sure this is related because the query I changed doesn't use the multi-dho-layout, but I fixed the bug and changed to a direct link (vs using ipfs-image-viewer) because load time is much faster

**Review by pugakn — COMMENTED** [review]
image

Something seems to be broken with the dho selector could you check it @arsenijesavic ?

**Comment by arsenijesavic** [comment]
Screenshot 2022-05-30 at 11 57 58
@pugakn fixed, but this was because images were not pinned so it took more time to load it not related to duplicate result :)

**Pull request merged**
